name: Build and deploy Python project to Azure Function App - fa-binance-15m-eu

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_PATH: 'fa-binance-15m-eu'   # <<< podsložka s funkcí
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into .python_packages (in subfolder)
        working-directory: ${{ env.APP_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target ".python_packages/lib/site-packages"

      - name: Zip only the app folder
        run: |
          cd $APP_PATH
          zip -r ../release.zip .   # zabal jen podsložku

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16D5243E86CB475D9A92AAE811FAB73C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9EEC048717314A2CB4A4ECE8F2AC4DF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_382C575C11BD4BB1A6C6ACD0A0BFBDFA }}

      - name: Deploy to Azure Functions (zip)
        uses: Azure/functions-action@v1
        with:
          app-name: 'fa-binance-15m-eu'
          package: 'release.zip'   # nasazujeme zip s obsahem podsložky
